ALTER TABLE CHAT_MESSAGES ADD COLUMN archivo_ruta TEXT DEFAULT '';
ALTER TABLE CHAT_MESSAGES ADD COLUMN archivo_nombre TEXT DEFAULT '';
ALTER TABLE CHAT_MESSAGES ADD COLUMN duracion_segundos REAL DEFAULT 0;
